z = int(input('Digite um numero para ver sua tabuada:'))

print('================')
print(f'{z}x 1 = {z * 1}')
print(f'{z}x 2 = {z * 2}')
print(f'{z}x 3 = {z * 3}')
print(f'{z}x 4 = {z * 4}')
print(f'{z}x 5 = {z * 5}')
print(f'{z}x 6 = {z * 6}')
print(f'{z}x 7 = {z * 7}')
print(f'{z}x 8 = {z * 8}')
print(f'{z}x 9 = {z * 9}')
print(f'{z}x 10 = {z * 10}')
print('=================')